name: Auto Close Issues

on:
  issues:
    types: [labeled]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Close issues with specific labels
      uses: actions/github-script@v3
      with:
        script: |
          const label = context.payload.label.name;
          if (['completed', 'wontfix'].includes(label)) {
            const issue_number = context.payload.issue.number;
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              state: 'closed'
            });
          }